# Generated by Django 5.0.1 on 2024-01-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=200)),
                ('carga_horaria', models.CharField(max_length=8)),
                ('investimento', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Alunos',
            new_name='Aluno',
        ),
    ]
